---
apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  labels:
    name: cadvisor
  namespace: cadvisor
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  # - port: 5672
  - port: 8080
    name: exporter
    targetPort: exporter
    protocol: TCP
  selector:
    name: cadvisor
