---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra
  namespace: jaeger
spec:
  type: NodePort
  ports:
    - port: 9042
      nodePort: 30030
  selector:
    app: cassandra